from viz.recorder import (
    GEOMETRY_STEP_ORDER,
    PAIR_STEP_ORDER,
    SINGLE_STEP_ORDER,
    STEP_ORDER,
    PipelineRecorder,
    ensure_all_step_pngs_exist,
    ensure_step_pngs_exist,
)
from pipeline.features import FrameFeatures, compute_frame_features_cache
from viz.step_runner import (
    ensure_sequence_outputs_exist,
    export_all_stages,
    export_sequence_consecutive_pairs,
    export_single_frame_stages,
    export_single_pair_stages,
    iter_sequence_pairs,
)

# Re-export fusion helpers used with sequence export
from pipeline.fusion import FusedLandmarkMap, FusedLandmark, fused_world_points_homogeneous
from viz.match_classification import (
    MatchClassification,
    audit_record,
    classify_match_rejections,
)
from viz.overlays import (
    blend_photo_depth_colormap,
    canny_edges_bgr,
    depth_to_bgr_colormap,
    draw_classified_matches,
    draw_depth_scale_bar_bottom_right,
    draw_epipolar_outliers_with_lines,
    draw_epilines,
    draw_matches,
    draw_matches_masked,
    draw_keypoints,
    draw_inlier_outlier_matches,
    draw_rich_keypoints,
    depth_colormap_range_m,
    depth_to_bgr_red_near_blue_far,
    estimated_depth_visualization,
    grayscale_to_bgr,
    project_points_topdown,
    project_world_points_to_camera_uv_z,
    render_dense_depth_colormap,
    render_depth_histogram_panel,
    render_sparse_depth_pixels,
    render_trajectory_topdown,
    sparse_depth_error_heatmap,
)

__all__ = [
    "FrameFeatures",
    "compute_frame_features_cache",
    "PipelineRecorder",
    "STEP_ORDER",
    "SINGLE_STEP_ORDER",
    "PAIR_STEP_ORDER",
    "GEOMETRY_STEP_ORDER",
    "ensure_step_pngs_exist",
    "ensure_all_step_pngs_exist",
    "MatchClassification",
    "audit_record",
    "classify_match_rejections",
    "blend_photo_depth_colormap",
    "canny_edges_bgr",
    "depth_colormap_range_m",
    "depth_to_bgr_colormap",
    "depth_to_bgr_red_near_blue_far",
    "draw_depth_scale_bar_bottom_right",
    "draw_classified_matches",
    "draw_epipolar_outliers_with_lines",
    "draw_epilines",
    "draw_matches",
    "draw_matches_masked",
    "draw_keypoints",
    "draw_inlier_outlier_matches",
    "draw_rich_keypoints",
    "estimated_depth_visualization",
    "grayscale_to_bgr",
    "project_points_topdown",
    "project_world_points_to_camera_uv_z",
    "render_dense_depth_colormap",
    "render_depth_histogram_panel",
    "render_sparse_depth_pixels",
    "render_trajectory_topdown",
    "sparse_depth_error_heatmap",
    "export_all_stages",
    "export_sequence_consecutive_pairs",
    "export_single_frame_stages",
    "export_single_pair_stages",
    "ensure_sequence_outputs_exist",
    "iter_sequence_pairs",
    "FusedLandmarkMap",
    "FusedLandmark",
    "fused_world_points_homogeneous",
]
